export type EngineKind = "race" | "stream" | "falling" | "text" | "memory" | "multiplayer";

export type GameDef = {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: string;
  difficulty: "Easy" | "Medium" | "Hard" | "Expert";
  engine: EngineKind;
  icon: string;
  accent: string;
  gradient: string;
  players: number;
  rating: number;
  featured: boolean;
  createdOrder: number;
  instructions: string[];
  controls: string[];
  scoring: string;
  config: Record<string, unknown>;
};

export const CATEGORIES = [
  "Racing",
  "Arcade",
  "Practice",
  "Speed",
  "Multiplayer",
  "Educational",
  "Kids",
  "Programming",
  "Numbers",
  "Symbols",
  "Survival",
  "Challenge",
] as const;

export const GAMES: GameDef[] = [
  {
    slug: "type-race",
    name: "Type Race",
    description: "Race rivals down the neon straight by typing sentences at full speed.",
    longDescription:
      "Type Race is the flagship Type Arena mode. Every correct character pushes your vehicle forward while three AI rivals fight for the finish line. Keep your combo alive for a speed boost.",
    category: "Racing",
    difficulty: "Medium",
    engine: "race",
    icon: "🏎️",
    accent: "#f97316",
    gradient: "from-orange-500/30 via-rose-500/20 to-fuchsia-600/30",
    players: 18422,
    rating: 4.9,
    featured: true,
    createdOrder: 1,
    instructions: ["Type the sentence exactly as shown", "Wrong keys cost you speed", "Chain correct words to build a combo boost"],
    controls: ["Keyboard", "On-screen keyboard on mobile"],
    scoring: "Score = WPM × accuracy × combo multiplier + placement bonus.",
    config: { opponents: 3 },
  },
  {
    slug: "word-blitz",
    name: "Word Blitz",
    description: "Clear words before the timer eats them. Pure reflex typing.",
    longDescription:
      "Words flash onto the grid with their own countdown. Clear them fast, stack combos, and survive escalating levels where words get longer and timers get shorter.",
    category: "Arcade",
    difficulty: "Medium",
    engine: "stream",
    icon: "⚡",
    accent: "#22d3ee",
    gradient: "from-cyan-500/30 via-sky-500/20 to-indigo-600/30",
    players: 14310,
    rating: 4.8,
    featured: true,
    createdOrder: 2,
    instructions: ["Type any visible word and press space/enter", "Words expire — clear them first", "Every 10 clears raises the level"],
    controls: ["Keyboard"],
    scoring: "Score = word length × 10 × combo multiplier.",
    config: { startLife: 5 },
  },
  {
    slug: "zombie-typist",
    name: "Zombie Typist",
    description: "Shred the undead horde one word at a time across endless waves.",
    longDescription:
      "Zombies shamble toward your barricade with a word painted on their chest. Type it to drop them. Survive waves, melt bosses, and grab power-ups before your health runs out.",
    category: "Survival",
    difficulty: "Hard",
    engine: "falling",
    icon: "🧟",
    accent: "#84cc16",
    gradient: "from-lime-500/30 via-emerald-600/20 to-slate-800/40",
    players: 12890,
    rating: 4.8,
    featured: true,
    createdOrder: 3,
    instructions: ["Type the word above a zombie to destroy it", "Bosses need the full word typed twice as fast", "Grab ⚡ power-ups by typing them first"],
    controls: ["Keyboard"],
    scoring: "Score = kills × 25 + wave bonus + combo streak.",
    config: { theme: "zombie", lives: 5, boss: true },
  },
  {
    slug: "keyboard-defender",
    name: "Keyboard Defender",
    description: "Defend the core reactor from waves of word-coded drones.",
    longDescription:
      "A tower-defense twist on typing: drones dive at your base, each tagged with a word. Clear them before impact, bank accuracy bonuses, and face a boss every fifth wave.",
    category: "Arcade",
    difficulty: "Hard",
    engine: "falling",
    icon: "🛡️",
    accent: "#38bdf8",
    gradient: "from-sky-500/30 via-blue-600/20 to-violet-700/30",
    players: 9980,
    rating: 4.7,
    featured: true,
    createdOrder: 4,
    instructions: ["Type the drone's word to destroy it", "Protect your base integrity", "Accuracy above 95% grants a shield bonus"],
    controls: ["Keyboard"],
    scoring: "Score = drones destroyed × 30 + accuracy bonus.",
    config: { theme: "defender", lives: 6, boss: true },
  },
  {
    slug: "type-ninja",
    name: "Type Ninja",
    description: "Slice flying words mid-air before they escape the arena.",
    longDescription:
      "Words arc across the screen like thrown blades. Slice them with perfect typing, chase golden bonus words, and keep your combo chain unbroken.",
    category: "Arcade",
    difficulty: "Medium",
    engine: "falling",
    icon: "🥷",
    accent: "#f43f5e",
    gradient: "from-rose-500/30 via-red-600/20 to-slate-900/40",
    players: 11240,
    rating: 4.6,
    featured: true,
    createdOrder: 5,
    instructions: ["Type the word to slice it", "Golden words are worth triple", "Missing three words ends the run"],
    controls: ["Keyboard"],
    scoring: "Score = slices × 20 × combo, golden words ×3.",
    config: { theme: "ninja", lives: 3, special: true },
  },
  {
    slug: "falling-words",
    name: "Falling Words",
    description: "Catch words before they hit the floor. Classic, relentless, addictive.",
    longDescription:
      "The original arcade typing trainer. Words drop faster every level, lives are limited, and your combo multiplier decides whether you reach the global board.",
    category: "Arcade",
    difficulty: "Easy",
    engine: "falling",
    icon: "🌧️",
    accent: "#a855f7",
    gradient: "from-purple-500/30 via-fuchsia-500/20 to-indigo-700/30",
    players: 20150,
    rating: 4.9,
    featured: true,
    createdOrder: 6,
    instructions: ["Type a falling word to clear it", "Each miss costs one life", "Speed increases every level"],
    controls: ["Keyboard"],
    scoring: "Score = word length × 15 × combo multiplier.",
    config: { theme: "classic", lives: 3 },
  },
  {
    slug: "typing-challenge",
    name: "Typing Challenge",
    description: "A full paragraph, a full report card. Measure everything.",
    longDescription:
      "Type a complete paragraph and receive a deep breakdown: WPM, accuracy, correct and incorrect characters, consistency, and error map.",
    category: "Challenge",
    difficulty: "Medium",
    engine: "text",
    icon: "📜",
    accent: "#eab308",
    gradient: "from-amber-500/30 via-yellow-500/20 to-orange-600/30",
    players: 8620,
    rating: 4.5,
    featured: false,
    createdOrder: 7,
    instructions: ["Type the paragraph exactly", "Backspace is allowed", "The timer starts on your first keystroke"],
    controls: ["Keyboard"],
    scoring: "Score = WPM × accuracy².",
    config: { source: "paragraph", duration: 0 },
  },
  {
    slug: "speed-sprint",
    name: "Speed Sprint",
    description: "15 seconds. One goal: the highest WPM you have ever hit.",
    longDescription:
      "A pure burst mode. Fifteen seconds of common words, no mercy, global high scores. Perfect for warming up or chasing a personal record.",
    category: "Speed",
    difficulty: "Easy",
    engine: "text",
    icon: "💨",
    accent: "#10b981",
    gradient: "from-emerald-500/30 via-teal-500/20 to-cyan-600/30",
    players: 17770,
    rating: 4.8,
    featured: true,
    createdOrder: 8,
    instructions: ["Type as many words as possible in 15 seconds", "Accuracy still counts", "Beat your personal record"],
    controls: ["Keyboard"],
    scoring: "Score = WPM × 10 × accuracy.",
    config: { source: "words", duration: 15 },
  },
  {
    slug: "survival-typing",
    name: "Survival Typing",
    description: "One life. Infinitely harder words. How long can you last?",
    longDescription:
      "Words get longer, rarer and faster with every clear. You have a single life and a shrinking timer. Only the sharpest typists break five minutes.",
    category: "Survival",
    difficulty: "Expert",
    engine: "stream",
    icon: "💀",
    accent: "#ef4444",
    gradient: "from-red-600/30 via-rose-700/20 to-slate-900/40",
    players: 7410,
    rating: 4.7,
    featured: false,
    createdOrder: 9,
    instructions: ["Clear each word before its timer runs out", "One miss ends the run", "Difficulty ramps every 5 words"],
    controls: ["Keyboard"],
    scoring: "Score = survival time × difficulty tier.",
    config: { startLife: 1, ramp: "fast" },
  },
  {
    slug: "number-master",
    name: "Number Master",
    description: "Drill the number row: phone numbers, currency, dates, math.",
    longDescription:
      "A numeric precision trainer. Switch between random digits, phone numbers, currency amounts, dates and math expressions to master the number row and keypad.",
    category: "Numbers",
    difficulty: "Medium",
    engine: "stream",
    icon: "🔢",
    accent: "#0ea5e9",
    gradient: "from-sky-600/30 via-blue-700/20 to-slate-800/40",
    players: 6120,
    rating: 4.4,
    featured: false,
    createdOrder: 10,
    instructions: ["Type the numeric token shown", "Switch sub-modes any time", "Punctuation counts"],
    controls: ["Keyboard", "Numpad"],
    scoring: "Score = tokens cleared × 20 + accuracy bonus.",
    config: { tokenKind: "numbers", startLife: 5 },
  },
  {
    slug: "symbol-master",
    name: "Symbol Master",
    description: "Conquer the shift row: @ # $ % ^ & * ( ) and friends.",
    longDescription:
      "Symbols are where most typists lose accuracy. This drill targets shift combinations and bracket pairs until they become muscle memory.",
    category: "Symbols",
    difficulty: "Hard",
    engine: "stream",
    icon: "#️⃣",
    accent: "#c084fc",
    gradient: "from-violet-600/30 via-purple-700/20 to-slate-800/40",
    players: 5230,
    rating: 4.3,
    featured: false,
    createdOrder: 11,
    instructions: ["Type the symbol cluster shown", "Shift accuracy is tracked separately", "Clusters grow as you improve"],
    controls: ["Keyboard"],
    scoring: "Score = clusters cleared × 30.",
    config: { tokenKind: "symbols", startLife: 5 },
  },
  {
    slug: "sentence-sprint",
    name: "Sentence Sprint",
    description: "Full sentences across seven categories, timed and scored.",
    longDescription:
      "Choose a category — general, business, technology, education, science, quotes or programming — and sprint through real sentences.",
    category: "Practice",
    difficulty: "Medium",
    engine: "text",
    icon: "📝",
    accent: "#14b8a6",
    gradient: "from-teal-500/30 via-emerald-600/20 to-slate-800/40",
    players: 7980,
    rating: 4.6,
    featured: false,
    createdOrder: 12,
    instructions: ["Pick a category", "Type the sentence exactly", "Beat the target WPM"],
    controls: ["Keyboard"],
    scoring: "Score = WPM × accuracy × category multiplier.",
    config: { source: "sentences", duration: 60, categories: true },
  },
  {
    slug: "code-typing",
    name: "Code Typing",
    description: "Snippets in JS, Python, HTML, CSS, SQL, Java and C++.",
    longDescription:
      "Built for developers: real code with real punctuation. Indentation is handled for you so you can focus on symbols, brackets and speed.",
    category: "Programming",
    difficulty: "Expert",
    engine: "text",
    icon: "💻",
    accent: "#60a5fa",
    gradient: "from-blue-600/30 via-indigo-700/20 to-slate-900/40",
    players: 9340,
    rating: 4.8,
    featured: true,
    createdOrder: 13,
    instructions: ["Pick a language", "Type the snippet including symbols", "Newlines auto-advance"],
    controls: ["Keyboard"],
    scoring: "Score = WPM × accuracy × language difficulty.",
    config: { source: "code", duration: 90 },
  },
  {
    slug: "typing-memory",
    name: "Typing Memory",
    description: "Memorise a word sequence, then reproduce it blind.",
    longDescription:
      "A cognitive twist: a sequence flashes on screen, disappears, and you must type it back in order. Sequences grow one word per round.",
    category: "Educational",
    difficulty: "Hard",
    engine: "memory",
    icon: "🧠",
    accent: "#f472b6",
    gradient: "from-pink-500/30 via-rose-600/20 to-purple-700/30",
    players: 4870,
    rating: 4.5,
    featured: false,
    createdOrder: 14,
    instructions: ["Memorise the words shown", "They vanish after a few seconds", "Type them back separated by spaces"],
    controls: ["Keyboard"],
    scoring: "Score = rounds survived × sequence length × 50.",
    config: { startLength: 3 },
  },
  {
    slug: "multiplayer-arena",
    name: "Multiplayer Arena",
    description: "Real-time 1v1, 4-player and 8-player typing battles.",
    longDescription:
      "Matchmaking, private rooms, ranked ladder and live race tracks. Opponents are simulated until the realtime server is attached — the client is already wired for it.",
    category: "Multiplayer",
    difficulty: "Hard",
    icon: "🌐",
    engine: "multiplayer",
    accent: "#fb7185",
    gradient: "from-rose-500/30 via-fuchsia-600/20 to-indigo-700/30",
    players: 15620,
    rating: 4.9,
    featured: true,
    createdOrder: 15,
    instructions: ["Pick a room size", "Wait for matchmaking", "Type the passage faster than everyone else"],
    controls: ["Keyboard"],
    scoring: "Ranked points based on placement, WPM and accuracy.",
    config: { sizes: [2, 4, 8] },
  },
  {
    slug: "kids-typing",
    name: "Alphabet Adventure",
    description: "Friendly letter-by-letter practice for young typists.",
    longDescription:
      "Big letters, cheerful words and zero pressure. Designed for kids learning the keyboard for the first time, with short words and generous timers.",
    category: "Kids",
    difficulty: "Easy",
    engine: "stream",
    icon: "🦄",
    accent: "#fbbf24",
    gradient: "from-amber-400/30 via-pink-400/20 to-sky-500/30",
    players: 6650,
    rating: 4.7,
    featured: false,
    createdOrder: 16,
    instructions: ["Type the big friendly word", "Take your time — timers are long", "Collect stars for every 5 words"],
    controls: ["Keyboard"],
    scoring: "Score = words cleared × 10.",
    config: { bank: "easy", startLife: 9, slow: true },
  },
];

export function getGame(slug: string): GameDef | undefined {
  return GAMES.find((g) => g.slug === slug);
}

export const DIFFICULTY_ORDER: Record<string, number> = { Easy: 1, Medium: 2, Hard: 3, Expert: 4 };
